[alias]
docs = "doc --workspace --all-features --no-deps"

[target.x86_64-pc-windows-msvc]
rustflags = ["-Clink-arg=/STACK:10000000"]

[target.i686-pc-windows-msvc]
rustflags = ["-Clink-arg=/STACK:10000000"]
